### PR TITLE
Feature 15 shopping cart cart item relation Fix

### PR DESCRIPTION
**Pull request by Bastian1998**
Fixed documentation typo (snake_case to camelCase
image

Fixed relations between cart and cart item (minimal changes in cart-item entity)
image

Fixed user_id null bug
image

Implemented method to get all items from a cart with id
image
image

### CODE REVIEW

**Comment by Bastian1998** [comment]
@ChachoPacho  El cambio en la entidad de cart-item fue minimo pero para que quede como la documentacion : 
image

El tipo de cartId en tu entidad deberia ser de tipo Cart y no number (No lo cambie porque funciona y tu controller depende de que sea number)

**Comment by ChachoPacho** [comment]
## Unnecessary Fix 

The [Official Documentation](https://typeorm.io/#/many-to-one-one-to-many-relations) says
> If you want to use @OneToMany, @ManyToOne is required. However, the inverse is not required: If you only care about the @ManyToOne relationship, you can define it without having @OneToMany on the related entity.

Therefore, the relation created in `Cart` is unnecessary, besides that https://github.com/RooftopAcademy/rooftend/pull/128/commits/7bdff895b30c617987713e466b36a0e5e0ac1d29 generates conflict with the api `/carts/{cartId}/items` already created in the __controller__ of `CartItem` which has exactly the same function that the commit wants to implement.

## Recommendation

Create a new Pull Request that only implements `Fixed documentation typo (snake_case to camelCase)`

**Comment by Bastian1998** [comment]
Hola @ChachoPacho  podemos hablarlos depues por discord? tenes razon que el metodo de obtener los cart-items de un cart es inecesario porque ya tiene ese el comportamiento el cart-items, pero me quedo dudas con respecto a las relaciones

**Comment by ChachoPacho** [comment]
Por qué mergearon esto si fue rechazado?

**Pull request closed without merging**
